name: VyOS Build

on:
  repository_dispatch:
    types:
      - ifttt
      - curl
  
env:
  BUILD_VERSION: ${{ github.event.client_payload.version }}
  WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
  WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
  
jobs:
  check-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checking for build version
        if: env.BUILD_VERSION == ''
        run: |
          echo "No build version supplied by webhook!"
          exit 1
      - name: Check for secrets
        if: ${{ env.WEBDAV_USER == '' || env.WEBDAV_PASS == '' }}
        run: |
          echo "Some or all secrets missing!
          exit 1
  iso-build:
    needs: check-vars
    runs-on: ubuntu-latest
    container: 
      image: vyos/vyos-build:equuleus
      options: --privileged
    steps:
      - name: Clone VyOS Build repo
        run: git clone -b ${{ env.BUILD_VERSION }} --single-branch https://github.com/vyos/vyos-build .
      - name: configure build
        run: ./configure --architecture amd64 --build-by "arthur@tuckerfami.ly" --build-type release --version ${{ env.BUILD_VERSION }}
      - name: Build ISO
        run: sudo make iso
      - name: Upload to WebDAV
        run: curl --silent --show-error --fail --basic --user '${{ env.WEBDAV_USER }}:${{ env.WEBDAV_PASS }}' -T './build/vyos-${{ env.BUILD_VERSION }}-amd64.iso' 'https://myfiles.fastmail.com/File%20Share/public/builds/vyos-${{ env.BUILD_VERSION }}-amd64.iso'
