name: VyOS Build

on:
  workflow_dispatch:
  
jobs:
  vyos-build:
    runs-on: ubuntu-latest
    container: 
      image: vyos/vyos-build:equuleus
      volumes:
        - vyos:/vyos
      options: --privileged
#        - --sysctl net.ipv6.conf.lo.disable_ipv6=0
    steps:
      - name: change directory to /vyos
        run: cd /vyos
      - name: getting current directory
        run: pwd
      - name: Clone VyOS Build repo
        run: git clone -b 1.3.2 --single-branch https://github.com/vyos/vyos-build
      - name: change directory to ./vyos-build
        run: cd ./vyos-build
      - name: getting current directory
        run: pwd
      - name: configure build
        run: ./configure --architecture amd64 --build-by "arthur@tuckerfami.ly"
      - name: make iso
        run: sudo make iso
      - name: list build dir
        run: ls /vyos/build
