name: VyOS Build

on:
  push:
  workflow_dispatch:
  
env:
  BUILD_VERSION: 1.3.2
  
jobs:
  vyos-build:
    runs-on: ubuntu-latest
    container: 
      image: vyos/vyos-build:equuleus
      volumes:
        - vyos:/vyos
      options: --privileged
    steps:
      - name: Clone VyOS Build repo
        run: git clone -b $BUILD_VERSION --single-branch https://github.com/vyos/vyos-build .
      - name: configure build
        run: ./configure --architecture amd64 --build-by "arthur@tuckerfami.ly" --build-type release --version $BUILD_VERSION
      - name: make iso
        run: sudo make iso
      - name: list build dir
        run: ls ./build
