name: VyOS Build

on:
  workflow_dispatch:
  
jobs:
  # vyos-build container
  container-job:
    runs-on: ubuntu-latest
    container: 
      image: vyos/vyos-build:equuleus
      volumes:
        - vyos:/vyos
      options:
        - --privileged
        - --workdir /vyos
#        - --sysctl net.ipv6.conf.lo.disable_ipv6=0
    steps:
      - name: Clone Repo
        run: git clone -b 1.3.2 --single-branch https://github.com/vyos/vyos-build
      - name: Configure build
        run: configure --architecture amd64 --build-by "arthur@tuckerfami.ly"
      - name: make iso
        run: sudo make iso
      - name: List build dir
        run: ls /vyos/build
